---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# project summary

The goal of project is to implement and investigate the behaviour of the Wilcoxon Rank Sum test statistic on pairs of sample drawn from the same population as against pairs of samples drawn from  different population distributions. The project is aimed to study the variation of this test statistic with the two cases and to examine the strength of the test as a dependant on the underlying sample.

I will also examine the behaviour of the test statistic if the two samples are from a symmetric distribution or not.

### Questions asked

  1. How does symmetry of the population distribution relate to the rejection rates of the test?
  2. How does the difference in sample size affect the rejection rate?
  3. For non-symmetric distribution, how does the difference in sample sizes affect the power of the test.

# Links

 * [Link to Presentation Slides](https://github.com/ST541-Fall2018/AsanteEmmanuel-project-wilcoxon/blob/master/Location-Shift%20and%20Rejection%20Rates%20in%20Wilcoxon%20Rank%20Sum.pdf)
 * [Link to Project Report](https://github.com/ST541-Fall2018/AsanteEmmanuel-project-wilcoxon/blob/master/Report/Wilcoxon_Project_Report.pdf)

# Navigation of Code file: Wilcoxon_code.Rmd

You need the `tidyverse` package and the `rsample` package to run the code file.

I wrote the code in such a way that to go through it, you only need to run code from chunk to chunk sequentially. You do not need to run any function before the other functions work.

# Wilcoxon One Table Function

### Arguments

  * **table_length** : This is the number of rows you want the simulated dataframe to have
  * **sample_from** : This is the probability distribution that we want to take the two samples from
  * **alpha** : The significance level. We compare the p-value to this. The value of this goes into the the `Reject` column on the output dataframe called one_table
  * **naive difference** : This parameter ensures that the sample size difference is at least this value on average.
  
  
### Values(Output)
The output is silent unless you specifically call for it.
  * **type_one_error_rate** A numeric scalar which represents the proportion of wilcoxon test p-values that resulted in a rejection of the Null Hypothesis.
  * **one_table** An object of type dataframe that contains the samples drawn, the p-value, and the Rejection decision (which is a logical vector).


### Other functions

All the other functions are similar to the wilcoxon_one_table. The slight difference is that they have been more specifically tailored to take the parameters of specific distributions as arguments. These functions are `wilcox_norm_table` and `wilcox_skew_table`. The `wilcox_skew_table`
function, however, takes two distributions; the Poisson and exponential. The function takes the poisson lambda as an argument and ensures that the exponential distribution from which the second sample is to be taken has the same variance as the poisson lambda specified.



